services:
  atividade-web:
    build: .
    container_name: atividade-web
    working_dir: /app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/atividades.db
      - PESSOA_SERVICE_URL=http://host.docker.internal:5002/api/professores
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/api/atividades/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5